/*
 * AI model Service Restful API
 *
 * This is an ai model service
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type BatchVideoRequest struct {
	Action    string                 `json:"action"`
	Videos    []VideoMeta            `json:"videos"`
	ModelName string                 `json:"model_name,omitempty"`
	Configure map[string]interface{} `json:"configure,omitempty"`
}

type VideoMeta struct {
	Url   string `json:"url"`
	Title string `json:"title,omitempty"`
}
